---
- name: Setup and Initialize Shard Databases
  hosts: db_shards
  become: yes
  tasks:
    - name: Create shard user
      mysql_user:
        name: shard_user
        password: "shard_password"
        priv: "*.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Setup shard replication (if needed)
      mysql_replication:
        mode: master
        login_user: root
        login_password: "{{ mysql_root_password }}"
        master_user: shard_user
        master_password: "shard_password"
        master_host: "{{ inventory_hostname }}"
        master_log_file: mysql-bin.000001
        master_log_pos: 107
