---
- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: true

- name: Set root password for MySQL
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host_all: yes
    state: present

- name: Create shard database
  mysql_db:
    name: "{{ mysql_database_name }}"
    state: present

- name: Create users table in shard database
  mysql_query:
    query: |
      CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(50),
        email VARCHAR(50),
        shard_key INT
      ) ENGINE=InnoDB;
    login_user: root
    login_password: "{{ mysql_root_password }}"
    db: "{{ mysql_database_name }}"
